accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
]

plant/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todos.urls')),
    path('accounts/',include('accounts.urls')),
]

todos/urls.py
from django.urls import path, include
from . import views

app_name = 'todos'

urlpatterns = [
    path('todos/', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:id>/', views.detail, name="detail"),
    path('<int:id>/delete', views.delete, name='delete'),
    path('<int:id>/update', views.update, name='update'),
    path('<int:id>/comment_create', views.comment_create, name='comment_create'),
    path('<int:id1>/comment_delete/<int:id2>/',
         views.comment_delete, name='comment_delete'),
    path('search/', views.search, name="search"),
    path('<int:id>/like/', views.like, name="like"),
    path('<int:write_id>/comment_like/<int:comment_id>',
         views.comment_like, name="comment_like"),
]

accounts/models.py
from django.db import models

# Create your models here.

todos/models.py
from django.db import models
from django.conf import settings
# Create your models here.


class Write(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    url = models.CharField(max_length=200)
    created_at = models.DateField(auto_now_add=True)
    cnt = models.IntegerField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_posts")


class Comment(models.Model):
    comment = models.CharField(max_length=100)
    created_at = models.DateField(auto_now_add=True)
    write = models.ForeignKey(Write, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    comment_like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="comment_like_posts")

todos/forms.py
from django import forms
from .models import Comment,Write

class WriteForm(forms.ModelForm):
    class Meta:
        model = Write
        fields = ('title','content','url')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('todos:index')
    else:
        form = UserCreationForm()
    context = {
        'form':form,
    }
    return render(request,'form.html',context)

def login(request):
    if request.method=='POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('todos:index')
    else:
        form = AuthenticationForm()
    context = {
        'form':form,
    }
    return render(request,'form.html',context)

def logout(request):
    auth_logout(request)
    return redirect('todos:index')

todos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Write, Comment
from .forms import WriteForm, CommentForm
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
import random
# Create your views here.


def index(request):
    writes = Write.objects.all()
    context = {
        'writes': writes
    }
    return render(request, 'index.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = WriteForm(request.POST)
        if form.is_valid():
            writes = form.save(commit=False)
            writes.user = request.user
            writes.cnt = 0
            writes.save()
            return redirect('todos:index')
    else:
        form = WriteForm()
    context = {
        'form': form,
    }
    return render(request, 'post.html', context)


def detail(request, id):
    write = get_object_or_404(Write, id=id)
    comment_form = CommentForm()
    write.cnt += 1
    write.save()
    context = {
        'write': write,
        'comment_form': comment_form,
    }
    return render(request, 'detail.html', context)


def delete(request, id):
    if request.method == 'POST':
        get_object_or_404(Write, id=id).delete()
        return redirect('todos:index')
    else:
        return redirect('todos:index')


def update(request, id):
    write = get_object_or_404(Write, id=id)
    if request.method == 'POST':
        form = WriteForm(request.POST, instance=write)
        if form.is_valid():
            form.save()

            return redirect('todos:detail', id)

    else:
        form = WriteForm(instance=write)
    context = {
        'form': form,
    }
    return render(request, 'post.html', context)


@require_POST
def comment_create(request, id):
    write = get_object_or_404(Write, id=id)
    comments_form = CommentForm(request.POST)
    if comments_form.is_valid():
        comment_ = comments_form.save(commit=False)
        comment_.write = write
        comment_.user = request.user
        comment_.save()
    return redirect('todos:detail', id)


@require_POST
def comment_delete(request, id1, id2):
    get_object_or_404(Comment, id=id2).delete()
    return redirect('todos:detail', id1)


def search(request):
    if request.method == 'POST':
        a = request.POST
        keyword = request.POST.get('keyword')
        writes = Write.objects.filter(title__icontains=keyword)
        context = {
            'writes': writes,
            'a': a
        }
        return render(request, 'search.html', context)
    else:
        write = Write.objects.all()
        context = {
            'writes': writes
        }
        return render(request, 'search.html', context)


def like(request, id):
    post = get_object_or_404(Write, id=id)
    user = request.user
    if user in post.like_users.all():
        post.like_users.remove(user)
    else:
        post.like_users.add(user)
    return redirect('todos:detail', id)


def comment_like(request, write_id, comment_id):
    post = get_object_or_404(Comment, id=comment_id)
    user = request.user
    if user in post.comment_like_users.all():
        post.comment_like_users.remove(user)
    else:
        post.comment_like_users.add(user)
    return redirect('todos:detail', write_id)

accounts/templates/form.html
{%extends 'base.html' %}
{%load bootstrap4%}
{% block body %}
    <form action="" method='post'>
        {%csrf_token%}
        {%bootstrap_form form%}
        <input type="submit" value='제출' class='btn btn-primary'>
    </form>
{%endblock%}

todos/templates/base.html
{%load bootstrap4%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    {%bootstrap_css%}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{%url 'todos:index'%}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {%if user.is_authenticated%}
                    <li class="nav-item">
                        <a class="nav-link disabled">{{user.username}}님</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'accounts:logout'%}">로그아웃</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'todos:create' %}">글쓰기</a>
                    </li>
                {%else%}
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'accounts:signup'%}">회원가입</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'accounts:login'%}">로그인</a>
                    </li>
                {%endif%}
            </ul>
            <form action = "{% url 'todos:search' %}" method='post' class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name='keyword'>
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    <div class="container">
        {%block body%}
        {%endblock%}
    </div>
    {%bootstrap_javascript jquery='full'%}
</body>
</html>

todos/templates/detail.html
{%extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
    <div class="jumbotron">
        <h1 class="display-4 text-center">{{write.title}}</h1>
        <img src="{{write.url}}" style = "width: 20rem; height: 30rem">
        <p class="lead text-center">{{write.content}}</p>
        {% if user in write.like_users.all %}
            <a href="{% url 'todos:like' write.id %}">좋아요 취소</a>
        {% else %}
            <a href="{% url 'todos:like' write.id %}">좋아요 </a>
        {% endif %}
        {%if user == write.user %}
            <a href="{%url 'todos:update' write.id%}" class='btn btn-warning'>수정</a>
            <form action="{%url 'todos:delete' write.id%}" method='post' class='d-inline'>
                {% csrf_token %}
                <input type="submit" value='삭제' class = 'btn btn-danger'>
            </form>
        {%endif%}
        <hr class="my-4">
        {%if user.is_authenticated%}
            <form action="{%url 'todos:comment_create' write.id%}" method='post'>
                {%csrf_token%}
                {%bootstrap_form comment_form%}
                <input type="submit" value='댓글작성' class='btn btn-primary'>
            </form>
        {%endif%}
        {%for comment in write.comment_set.all%}
            <div class="alert alert-info d-flex justify-content-between my-3" role="alert">
                {{comment.user}} : {{comment.comment}}
                <form action="{%url 'todos:comment_delete' write.id comment.id%}" method='post'>
                    {%csrf_token%}
                    <small>{{comment.created_at}}</small>
                    {%if user == comment.user %}
                    <input type="submit" value='삭제' class='btn btn-dark'>
                    {%endif%}
                    {% if user in comment.comment_like_users.all %}
                        <a href="{% url 'todos:comment_like' write.id comment.id %}">댓글좋아요취소</a>
                    {% else %}
                        <a href="{% url 'todos:comment_like' write.id comment.id %}">댓글좋아요</a>
                    {% endif %}
                </form>
            </div>
        {%endfor%}
    </div>
{% endblock %}

todos/templates/index.html
{%extends 'base.html'%}
{%block body%}
    <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">글제목</th>
            <th scope="col">작성자</th>
            <th scope="col">작성날짜</th>
            <th scope="col">조회수</th>
          </tr>
        </thead>
        <tbody>
            {% for form in writes %}
            <form action="{%url 'todos:delete' form.id%}" method='post'>
                {%csrf_token%}

                    
                    <tr>
                        <th scope="row">1</th>
                        <td><a href="{%url 'todos:detail' form.id%}">{{form.title}}</a></td>
                        
                        <td>{{form.user}}</td>
                        <td>{{form.created_at}}</td>
                        {% if user == form.user %}
                            <td>{{form.cnt}} <input type='submit' class='btn btn-danger' value='삭제'></td>
                        {% else %}
                        <td>{{form.cnt}}</td>
                        {%endif%}
                    </tr>
                  
            </form>
            {% endfor %}
          
        </tbody>
    </table>
 
{%endblock%}

todos/templates/post.html
{%extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
    <form action="" method='post'>
        {%csrf_token%}
        {%bootstrap_form form%}
        <input class='btn btn-primary' type='submit'>
    </form>
{% endblock %}

todos/templates/search.html
{% extends 'base.html' %}
{% block body %}
{% for write in writes %}
<div class="d-flex align-items-center mb-2">
  <a href="{% url 'todos:detail' write.id %}"><h3 id='title' class="card-title mr-5">{{write.title}}</h3></a>
  &nbsp;&nbsp;&nbsp;
</div>
{% endfor %}
{% endblock %}